# Source machine
source:
  os: "ubuntu"                     # OS
  version: "16.04"                 # OS version (optional)
  type: "generic"                  # Type of source server

  # How to setup machine
  setup:
    test: true                     # Do tests
  finish:
    destroy: true                  # Destroy instance automatically

  # Generic target
  generic:
    ip: "10.0.4.10"                # Instance IPv4 address

  # SSH details
  ssh:
    username: false                # Username (false = automatic)
    key: "~/.ssh/captain/id_rsa"   # Keyfile used to SSH

# Destination machine
destination:
  os: "ubuntu"                     # OS
  version: "16.04"                 # OS version (optional)
  type: "generic"                  # Type of destination server

  # How to setup machine
  setup:
    create: false                  # Create instance automatically
    environment: false				     # Prepare installer environment (via Puppet)
    test: true                     # Do tests
  finish:
    destroy: false                 # Destroy instance automatically

  # Generic target
  generic:
    ip: "10.0.4.20"                # Instance IPv4 address

  # AWS target
  aws:
    type: "t2.micro"               # Instance type
    ami: "25a97a4a"                # Amazon AMI ID
    key: "captain"                 # Keypair name (already added to AWS CLI)
    security: "captain"            # Security group name
    instance: ""                   # Instance ID (if already running)

  # SSH details
  ssh:
    username: false                # Username (false = automatic)
    key: "~/.ssh/captain/id_rsa"   # Keyfile used to SSH